version: '3.1'
services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: WEBSITE
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      LANG: C.UTF-8
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_data:  